### PR TITLE
metanorma/ci#172 add to cimas

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse please feel free to review

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP ! Actually the repository has been transferred to https://github.com/iho-ohi/C-17-Publication , so we need to fork it now. Let me fork it and delete this one.

**Comment by ronaldtse** [comment]
@CAMOBAP actually we already have it here: https://github.com/metanorma/C-17-Publication

Can you move this PR (the changes) there? Then I'll delete this one. Thanks.

**Comment by ronaldtse** [comment]
@CAMOBAP this is a client repository so it should only have one job. Can you help make this in the forked repository? Thanks.

**Comment by CAMOBAP** [comment]
Sure, @ronaldtse please give me write access to https://github.com/metanorma/C-17-Publication

**Comment by ronaldtse** [comment]
@CAMOBAP access fixed. Thanks!

**Pull request closed without merging**
